import CoreML
import Foundation
import Testing
import Tokenizers

@testable import ActionRouter
@testable import ActionRouterCoreML

/// Directory produced by `tools/convert/convert_e5.py` (contains the
/// .mlpackage and tokenizer/). Tests that need the real model are gated on
/// this environment variable so machines without the artifacts skip them:
///
///     ACTIONROUTER_E5_DIR=tools/convert/build swift test
private var e5Directory: URL? {
    ProcessInfo.processInfo.environment["ACTIONROUTER_E5_DIR"]
        .map { URL(fileURLWithPath: $0, isDirectory: true) }
}

private func makeProvider() throws -> CoreMLEmbeddingProvider {
    let directory = try #require(e5Directory)
    return CoreMLEmbeddingProvider(
        modelURL: directory.appendingPathComponent("MultilingualE5Small.mlpackage"),
        tokenizerDirectory: directory.appendingPathComponent("tokenizer")
    )
}

// The Swift tokenizer must produce exactly the same token IDs as the
// Hugging Face reference tokenizer (fixtures generated by tools/convert).
@Test(.enabled(if: e5Directory != nil))
func tokenizerMatchesReferenceImplementation() async throws {
    struct Fixture: Decodable {
        let text: String
        let ids: [Int]
    }
    let fixtureURL = try #require(
        Bundle.module.url(forResource: "tokenizer_parity", withExtension: "json", subdirectory: "Fixtures")
    )
    let fixtures = try JSONDecoder().decode([Fixture].self, from: Data(contentsOf: fixtureURL))
    #expect(!fixtures.isEmpty)

    let directory = try #require(e5Directory)
    let tokenizer = try await AutoTokenizer.from(
        modelFolder: directory.appendingPathComponent("tokenizer")
    )
    for fixture in fixtures {
        let ids = tokenizer.encode(text: fixture.text)
        #expect(ids == fixture.ids, "tokenization mismatch for: \(fixture.text)")
    }
}

@Test(.enabled(if: e5Directory != nil))
func embeddingsAreNormalizedAndDiscriminative() async throws {
    let provider = try makeProvider()
    let vectors = try await provider.embed(
        [
            "convert this song to wav format",
            "convertir esta canción a wav",
            "remove the background from this picture",
        ],
        purpose: .query
    )
    #expect(vectors.count == 3)
    #expect(vectors[0].count == 384)

    // Model output is baked-in normalized.
    for vector in vectors {
        let norm = VectorMath.dot(vector, vector)
        #expect(abs(norm - 1) < 1e-2, "expected unit norm, got \(norm)")
    }

    // Cross-language paraphrases must be closer than unrelated texts.
    let paraphrase = VectorMath.dot(vectors[0], vectors[1])
    let unrelated = VectorMath.dot(vectors[0], vectors[2])
    #expect(paraphrase > unrelated + 0.05)
}

@Test(.enabled(if: e5Directory != nil))
func coreMLProviderRoutesCrossLingualQueries() async throws {
    let provider = try makeProvider()
    var configuration = RouterConfiguration.default
    configuration.semantic = .e5

    let router = ActionRouter(configuration: configuration, embeddingProvider: provider)
    await router.register([
        Action(
            id: "remove-background",
            name: "Remove image background",
            description: "Removes the background from a picture."
        ),
        Action(
            id: "audio-to-wav",
            name: "Convert audio to WAV",
            description: "Converts audio files to the WAV format."
        ),
        Action(
            id: "compress-video",
            name: "Compress video",
            description: "Reduces the file size of a video."
        ),
        Action(
            id: "merge-pdf",
            name: "Merge PDF documents",
            description: "Combines several PDF files into one."
        ),
    ])
    let status = await router.semanticStatus
    #expect(status == .ready)

    // Catalan, Spanish and Chinese queries with no lexical overlap.
    let catalan = try await router.route("treu el fons de la foto")
    #expect(catalan.match?.action.id == "remove-background")

    let spanish = try await router.route("quiero que este video pese menos")
    #expect(spanish.match?.action.id == "compress-video")

    let chinese = try await router.route("把这些PDF合并成一个文件")
    #expect(chinese.match?.action.id == "merge-pdf")

    // Out of scope must abstain.
    let pizza = try await router.route("order a pizza for dinner")
    guard case .abstained = pizza.decision else {
        Issue.record("Expected abstention, got \(pizza.decision)")
        return
    }
}
